on:
  workflow_call:
    inputs:
      boundary_folder:
        required: true
        type: string

jobs:
  check_boundaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Changed files:"
          for file in ${ALL_CHANGED_FILES}; do
            echo "- $file"
          done
      
      - name: Listing files outside ${{ inputs.boundary_folder }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          files_outside_boundary=()

          for file in ${ALL_CHANGED_FILES}; do
            file_path="$(realpath "$file")"

            if [[ ! "$file_path" =~ ^"${{ inputs.boundary_folder }}" ]]; then
              files_outside_boundary+=("$file_path")
            fi
          done

          echo "::set-output name=outside_boundary_files::$files_outside_boundary"