on: 
  pull_request: 
    branches: 
      - develop
    paths:
      'terraform/**'
  
jobs:
  call_check_boundaries:
    name: Check PR Boundaries
    uses: ./.github/workflows/check-boundaries-template.yml
    with:
      boundary_folder: terraform

  plan_terraform:
    name: Plan Terraform deployment
    needs: call_check_boundaries
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEV_PIPELINE_ROLE }}
          role-session-name: terraform-ci-job
          aws-region: ${{ vars.AWS_REGION }}

      # Passo de lint do Terraform
      - name: Terraform Lint
        run: terraform fmt -check

      # Passo de validação do Terraform
      - name: Terraform Validate
        run: terraform validate

      # Passo de inicialização do terraform para o ambiente de dev
      - name: Terraform Initialization
        working-directory: terraform/env/dev
        run: terraform init

      # Passo de plan do terraform para o ambiente de dev
      - name: Terraform Plan
        working-directory: terraform/env/dev
        run: terraform plan -out=terraform.plan

      # Passo de upload do arquivo de plan do terraform
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: terraform/env/dev/terraform.plan